version: 2
jobs:
    build:
        working_directory: ~/pubnative/pubnative-hybid-ios-sdk
        shell: /bin/bash --login -o pipefail
        macos:
            xcode: "12.0.0"
        steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                    - "65:e9:57:c4:ba:ab:07:4d:b9:8a:1b:55:16:38:93:7f"
            - run:
                name: Publish private repo into public one
                command: |
                  if [ "${CIRCLE_BRANCH}" == "master" ] ; then
                    cd ~/pubnative
                    git clone git@github.com:pubnative/HyBid-Public-Clone.git publicRepoWePushInto
                    cd publicRepoWePushInto
                    git remote add private-hybid ~/pubnative/pubnative-hybid-ios-sdk
                    git fetch private-hybid --tags
                    git merge --allow-unrelated-histories private-hybid/master --strategy-option=theirs -X rename-threshold=100% -m "Some message for merge editor."
                    git rm .circleci/* -f

                    git merge HEAD &> /dev/null
                    result=$?
                    if [ $result -ne 0 ]
                    then
                        git merge --continue
                    fi

                    git push
                    git remote remove private-hybid
                  fi
